services:
  mysql-master:
    image: mysql:8.4
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/master/conf.d:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
      - mysql-master-data:/var/lib/mysql

  mysql-replica1:
    build: ./mysql/replica1
    container_name: mysql-replica1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    depends_on:
      - mysql-master
    volumes:
      - ./mysql/replica1/conf.d:/etc/mysql/conf.d
      - ./mysql/replica1/setup:/docker-entrypoint-initdb.d
      - mysql-replica1-data:/var/lib/mysql

  mysql-replica2:
    build: ./mysql/replica2
    container_name: mysql-replica2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3308:3306"
    depends_on:
      - mysql-master
    volumes:
      - ./mysql/replica2/conf.d:/etc/mysql/conf.d
      - ./mysql/replica1/setup:/docker-entrypoint-initdb.d
      - mysql-replica2-data:/var/lib/mysql

  app:
    build: ./app
    container_name: api-app
    ports:
      - "3000:3000"
    depends_on:
      - mysql-master
    environment:
      DB_HOST: proxysql
      DB_PORT: 6033
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_NAME: app_db

  proxysql:
    image: proxysql/proxysql:2.7.3
    container_name: proxysql
    ports:
      - "6033:6033"  # SQL接続ポート
      - "6032:6032"  # 管理用ポート
    volumes:
      - ./proxysql/proxysql.cnf:/etc/proxysql.cnf
    depends_on:
      - mysql-master
      - mysql-replica1
      - mysql-replica2

volumes:
  mysql-master-data:
  mysql-replica1-data:
  mysql-replica2-data:
